---
title: "Task1"
author: "Kirill Tumanov"
date: "18 09 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```
##Load Data
```{r}
url1 <- "http://data.ssb.no/api/v0/dataset/95274.csv?lang=no"
url2 <- "http://data.ssb.no/api/v0/dataset/95276.csv?lang=no"
data_1 <- read.csv(url1,sep = ";",dec = ",")
data_2 <- read.csv(url2,sep = ";",dec = ",")
```
#Change names of column
```{r}
colnames <- c("region", "date", "variable", "value")
colnames(data_1) <- colnames
colnames(data_2) <- colnames
```
#Change the data
```{r}
data_1 <- data_1 %>%
  mutate(date = gsub("M","01",date)) %>%
  mutate (date = lubridate::ydm(date))
data_2 <- data_2 %>%
  mutate(date = gsub("M","01",date)) %>%
  mutate (date = lubridate::ydm(date))
```
#Recode the Norwegian labels into English
```{r}
data_1 <- data_1 %>%
  mutate(variable = recode (variable,
                          "Kapasitetsutnytting av senger (prosent)" = "Beds percentage capacity utilization",
                          "Kapasitetsutnytting av rom (prosent)" = "Rooms percentage capacity utilization",
                          "Pris per rom (kr)" = "Price per room" ))
data_2 <- data_2 %>%
  mutate(variable = recode (variable,
                          "Kapasitetsutnytting av senger (prosent)" = "Beds percentage capacity utilization",
                          "Kapasitetsutnytting av rom (prosent)" = "Rooms percentage capacity utilization",
                          "Pris per rom (kr)" = "Price per room" ))
data_1$value[data_1$value == 0] <- NA
data_2$value[data_2$value == 0] <- NA
```
#Join data
```{r}
data_1 <- data_1 %>%
  mutate (region = as.character(region),
         value = as.numeric(value))
data_2 <- data_2 %>%
  mutate (region = as.character(region),
         value = as.numeric(value))
total_data <- merge(data_1,data_2, by = c ("date","variable"))
```
#calculate the difference between county average room price and the national average room price per month
```{r}
total_data <- total_data %>%
  mutate(value_deduct = value.x - value.y)
means_region <- total_data %>%
  filter(variable == "Price per room") %>%
  group_by(region.x) %>%
  summarise(mean = mean(value_deduct, na.rm = TRUE))
means_years <- total_data %>%
  filter(variable == "Price per room") %>%
  group_by(lubridate::year(date)) %>%
  summarise(mean = mean(value_deduct,na.rm = TRUE))
```
##Plot
```{r}
total_data %>%
  filter(variable=="Price per room") %>%
  filter(region.x=="19 Troms - Romsa") %>%
  ggplot(aes(x=date, y=value_deduct)) +
  geom_line(col="blue")
```

##Question
```{r}
library(reshape2)
dat_expand <- dcast(total_data,date + region.x ~ variable, value.var = "value.x")
names(dat_expand) [3:5] <- c ("roomCap","bedCap","priceRoom")
coler_county <- dat_expand %>%
  filter(date >= as.Date("2010-01-01")) %>%
  group_by(region.x) %>%
  summarise(cor = cor(x = roomCap, y=priceRoom,
                           use = "pairwise.complete.obs",
                           method = "pearson"))
```



